### PR TITLE
Add cross-env to build (#2)

### PR DESCRIPTION
**Pull request by beetosu**
## Proposed changes
--------------------
Added the [cross-env](https://www.npmjs.com/package/cross-env) to package.json and updated the build scripts to utilize it, making it possible for Windows users to run the project.

## Types of changes
--------------------
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist
--------------------
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

- [x] My changeset covers only what is described above (no extraneous changes)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged downstream

## Further comments
--------------------
It looks like the installation updated the name of the project, I'm not entirely sure why.

### CODE REVIEW

**Comment by MikeDrewitt** [comment]
This is perfect. Just rebase against the latest master please to remove conflicts from the `package-lock.json`

**Comment by beetosu** [comment]
Sorry, but I'm not super familiar with rebasing, would that be like `git rebase cross-env master`?

**Comment by daviddob** [comment]
Here's a great (and quick) guide to rebasing across forks - itll be less complicated within a single origin (just fetch + rebase) but this should get you sorted in this instance https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa

Just remember when rebasing to checkout your branch `cross-env` instead of master like it references

**Comment by beetosu** [comment]
Alright, it took a second, but I think I was able to do it, thanks for the help!

**Review by MikeDrewitt — APPROVED** [review]

**Pull request merged**
